package dev.dragonslegacy.config;

import dev.dragonslegacy.DragonsLegacyMod;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import org.jetbrains.annotations.Nullable;

import java.nio.charset.StandardCharsets;
import java.util.UUID;

/**
 * Utility class that resolves {@link AttributeEntry} objects from YAML config into
 * live Minecraft {@link Attribute} holders, {@link Identifier} modifier IDs, and
 * {@link AttributeModifier.Operation} values.
 *
 * <p>All methods log warnings for invalid/unknown entries and never throw.
 */
public final class ConfigAttributeParser {

    /** Default operation string used both as a YAML fallback and in seed generation. */
    private static final String DEFAULT_OPERATION = "add_value";

    private ConfigAttributeParser() {}

    // -------------------------------------------------------------------------
    // Attribute lookup
    // -------------------------------------------------------------------------

    /**
     * Resolves the {@link Holder} for the attribute referenced by {@code entry.id}.
     *
     * <p>If {@code entry.id} does not contain a colon, {@code "minecraft:"} is
     * prepended automatically (e.g. {@code "max_health"} → {@code "minecraft:max_health"}).
     *
     * @param entry the config entry to resolve
     * @return the attribute holder, or {@code null} if the entry is invalid or unknown
     */
    @Nullable
    public static Holder<Attribute> parseAttribute(AttributeEntry entry) {
        if (entry == null || entry.id == null || entry.id.isBlank()) {
            DragonsLegacyMod.LOGGER.warn("[Dragon's Legacy] Attribute entry has null/empty id – skipping.");
            return null;
        }
        // Auto-complete namespace: bare names become "minecraft:<name>"
        String rawId = entry.id.contains(":") ? entry.id : "minecraft:" + entry.id;
        Identifier id;
        try {
            id = Identifier.parse(rawId);
        } catch (Exception e) {
            DragonsLegacyMod.LOGGER.warn(
                "[Dragon's Legacy] Invalid attribute identifier '{}' – skipping: {}", rawId, e.getMessage());
            return null;
        }
        return BuiltInRegistries.ATTRIBUTE.getOptional(id)
            .map(attr -> (Holder<Attribute>) BuiltInRegistries.ATTRIBUTE.wrapAsHolder(attr))
            .orElseGet(() -> {
            DragonsLegacyMod.LOGGER.warn(
                "[Dragon's Legacy] Warning: Unknown attribute '{}' – skipping.", rawId);
            return null;
        });
    }

    // -------------------------------------------------------------------------
    // Modifier identifier
    // -------------------------------------------------------------------------

    /**
     * Derives a stable, deterministic {@link Identifier} for the attribute modifier
     * from the entry's {@code id} and {@code operation} fields.
     *
     * <p>The identifier is generated by calling
     * {@link UUID#nameUUIDFromBytes(byte[])} on the UTF-8 encoding of
     * {@code "<normalisedId>:<operation>"}.  This guarantees:
     * <ul>
     *   <li>Stable UUIDs across server reloads</li>
     *   <li>No conflicts between different attribute/operation combinations</li>
     *   <li>No need for server owners to manage UUID fields in YAML</li>
     * </ul>
     *
     * @param entry the config entry whose {@code id} and {@code operation} are used
     * @return a valid {@link Identifier}, or {@code null} if the entry has a null/empty id
     */
    @Nullable
    public static Identifier getModifierIdentifier(AttributeEntry entry) {
        if (entry == null || entry.id == null || entry.id.isBlank()) {
            DragonsLegacyMod.LOGGER.warn("[Dragon's Legacy] Attribute entry has null/empty id – skipping modifier identifier.");
            return null;
        }
        // Normalise the id the same way parseAttribute() does so the key is consistent.
        String normId = entry.id.contains(":") ? entry.id : "minecraft:" + entry.id;
        String op = (entry.operation != null) ? entry.operation.toLowerCase() : DEFAULT_OPERATION;
        String seed = normId + ":" + op;
        UUID uuid = UUID.nameUUIDFromBytes(seed.getBytes(StandardCharsets.UTF_8));
        // UUID strings contain only hex digits and dashes – both valid in Identifier paths.
        return Identifier.fromNamespaceAndPath("dragonslegacy", uuid.toString());
    }

    // -------------------------------------------------------------------------
    // Operation parsing
    // -------------------------------------------------------------------------

    /**
     * Parses the {@code operation} string from a config entry into an
     * {@link AttributeModifier.Operation} enum value.
     *
     * <p>Accepted values (case-insensitive):
     * <ul>
     *   <li>{@code "add_value"} → {@link AttributeModifier.Operation#ADD_VALUE}</li>
     *   <li>{@code "multiply_base"} → {@link AttributeModifier.Operation#ADD_MULTIPLIED_BASE}</li>
     *   <li>{@code "multiply_total"} → {@link AttributeModifier.Operation#ADD_MULTIPLIED_TOTAL}</li>
     * </ul>
     *
     * @param entry the config entry whose {@code operation} field is parsed
     * @return the resolved operation, or {@link AttributeModifier.Operation#ADD_VALUE} as fallback
     */
    public static AttributeModifier.Operation parseOperation(AttributeEntry entry) {
        if (entry == null || entry.operation == null) return AttributeModifier.Operation.ADD_VALUE;
        return switch (entry.operation.toLowerCase()) {
            case "multiply_base"  -> AttributeModifier.Operation.ADD_MULTIPLIED_BASE;
            case "multiply_total" -> AttributeModifier.Operation.ADD_MULTIPLIED_TOTAL;
            default -> {
                if (!DEFAULT_OPERATION.equalsIgnoreCase(entry.operation)) {
                    DragonsLegacyMod.LOGGER.warn(
                        "[Dragon's Legacy] Unknown operation '{}' for attribute '{}' – defaulting to add_value.",
                        entry.operation, entry.id);
                }
                yield AttributeModifier.Operation.ADD_VALUE;
            }
        };
    }
}
